// providers.js — API connection templates for ChatAI.
// Every connection uses an OpenAI-compatible chat-completions endpoint.
// Preset endpoints and default models are suggestions; any can be overridden.

export const CONNECTION_TYPES = {
  ollama: {
    id: "ollama",
    label: "Ollama API",
    prompt: "Connect to your own Ollama server via its OpenAI-compatible /v1/chat/completions endpoint. Use localhost, a tunnel, or a public server.",
    defaultEndpoint: "http://localhost:11434/v1/chat/completions",
    endpointHint: "http://localhost:11434/v1/chat/completions or https://your-server/v1/chat/completions",
    defaultModel: "llama3.2",
    keyLabel: "API key (optional)",
    keyHint: "Ollama ignores this unless an authenticating proxy requires it.",
    modelHint: "e.g. llama3.2, qwen2.5, gemma2, phi3, mistral",
    keyRequired: false,
    tags: ['local', 'fast', 'coding'],
    accent: "#34c759",
  },
  llamacpp: {
    id: "llamacpp",
    label: "llama.cpp Server",
    prompt: "Connect to a local llama.cpp server via its OpenAI-compatible /v1/chat/completions endpoint.",
    defaultEndpoint: "http://localhost:8080/v1/chat/completions",
    endpointHint: "http://localhost:8080/v1/chat/completions or https://your-server/v1/chat/completions",
    defaultModel: "llama-3.2-3b-instruct",
    keyLabel: "API key (optional)",
    keyHint: "llama.cpp ignores this unless an authenticating proxy requires it.",
    modelHint: "e.g. llama-3.2-3b-instruct, qwen2.5-7b-instruct, gemma-3-12b-it",
    keyRequired: false,
    tags: ['local', 'fast', 'coding'],
    accent: "#8b5cf6",
  },
  openai: {
    id: "openai",
    label: "OpenAI API",
    prompt: "Official OpenAI API.",
    defaultEndpoint: "https://api.openai.com/v1/chat/completions",
    defaultModel: "gpt-4o-mini",
    keyLabel: "OpenAI API key",
    keyHint: "sk-...",
    modelHint: "e.g. gpt-4o, gpt-4o-mini, o3-mini, o4-mini",
    keyRequired: true,
    keyUrl: "https://platform.openai.com/api-keys",
    tags: ['reasoning', 'vision', 'coding', 'write'],
    accent: "#10a37f",
  },
  anthropic: {
    id: "anthropic",
    label: "Anthropic Claude API",
    prompt: "Anthropic Claude API via an OpenAI-compatible proxy.",
    defaultEndpoint: "https://api.anthropic.com/v1/messages",
    defaultModel: "claude-3-5-sonnet-20241022",
    keyLabel: "Anthropic API key",
    keyHint: "sk-ant-...",
    modelHint: "e.g. claude-3-5-sonnet, claude-3-7-sonnet, claude-opus-4",
    keyRequired: true,
    keyUrl: "https://console.anthropic.com/settings/keys",
    tags: ['reasoning', 'write', 'coding', 'long_context'],
    accent: "#d97757",
  },
  gemini: {
    id: "gemini",
    label: "Google Gemini API",
    prompt: "Google Gemini API.",
    defaultEndpoint: "https://generativelanguage.googleapis.com/v1beta/openai/chat/completions",
    defaultModel: "gemini-2.5-pro-exp-03-25",
    keyLabel: "Google AI Studio key",
    keyHint: "Paste your API key",
    modelHint: "e.g. gemini-2.5-pro, gemini-2.0-flash, gemma-3-27b-it",
    keyRequired: true,
    keyUrl: "https://aistudio.google.com/app/apikey",
    tags: ['cheap', 'fast', 'vision', 'reasoning'],
    accent: "#4285f4",
  },
  azure: {
    id: "azure",
    label: "Azure OpenAI Service",
    prompt: "Azure OpenAI Service. Replace {endpoint} and {deployment} with your own values.",
    defaultEndpoint: "https://{your-resource}.openai.azure.com/openai/deployments/{deployment}/chat/completions?api-version=2024-10-21",
    defaultModel: "gpt-4o",
    keyLabel: "Azure API key",
    keyHint: "Paste your Azure OpenAI key",
    modelHint: "Deployment name, e.g. gpt-4o",
    keyRequired: true,
    keyUrl: "https://portal.azure.com/",
    tags: ['reasoning', 'vision', 'coding'],
    accent: "#0078d4",
  },
  bedrock: {
    id: "bedrock",
    label: "AWS Bedrock (proxy)",
    prompt: "AWS Bedrock via an OpenAI-compatible proxy/gateway.",
    defaultEndpoint: "https://bedrock-runtime.{region}.amazonaws.com/model/{model-id}/converse",
    defaultModel: "anthropic.claude-3-5-sonnet-20241022-v2:0",
    keyLabel: "Proxy API key",
    keyHint: "Paste proxy key (Bedrock itself uses AWS SigV4)",
    modelHint: "e.g. anthropic.claude-3-5-sonnet",
    keyRequired: true,
    keyUrl: "https://aws.amazon.com/bedrock/",
    tags: ['reasoning', 'write', 'coding'],
    accent: "#ff9900",
  },
  vertex: {
    id: "vertex",
    label: "Google Cloud Vertex AI",
    prompt: "Vertex AI via an OpenAI-compatible proxy or endpoint.",
    defaultEndpoint: "https://{region}-aiplatform.googleapis.com/v1/projects/{project}/locations/{region}/endpoints/openapi/chat/completions",
    defaultModel: "gemini-2.5-pro",
    keyLabel: "API key or proxy key",
    keyHint: "Paste your key",
    modelHint: "e.g. gemini-2.5-pro, claude-3-5-sonnet",
    keyRequired: true,
    keyUrl: "https://console.cloud.google.com/vertex-ai/",
    tags: ['reasoning', 'vision', 'coding'],
    accent: "#1a73e8",
  },
  moonshot: {
    id: "moonshot",
    label: "Moonshot Kimi API",
    prompt: "Moonshot Kimi API.",
    defaultEndpoint: "https://api.moonshot.cn/v1/chat/completions",
    defaultModel: "moonshot-v1-8k",
    keyLabel: "Moonshot API key",
    keyHint: "Paste your API key",
    modelHint: "e.g. moonshot-v1-8k, kimi-k2-0905-preview",
    keyRequired: true,
    keyUrl: "https://platform.moonshot.cn/console/api-keys",
    tags: ['long_context', 'coding', 'reasoning'],
    accent: "#a855f7",
  },
  zhipu: {
    id: "zhipu",
    label: "Zhipu GLM API",
    prompt: "Zhipu GLM API.",
    defaultEndpoint: "https://open.bigmodel.cn/api/paas/v4/chat/completions",
    defaultModel: "glm-4-plus",
    keyLabel: "Zhipu API key",
    keyHint: "Paste your API key",
    modelHint: "e.g. glm-4-plus, glm-4-air, glm-4-flash",
    keyRequired: true,
    keyUrl: "https://open.bigmodel.cn/usercenter/apikeys",
    tags: ['cheap', 'coding'],
    accent: "#3b82f6",
  },
  minimax: {
    id: "minimax",
    label: "MiniMax API",
    prompt: "MiniMax API.",
    defaultEndpoint: "https://api.minimaxi.com/v1/chat/completions",
    defaultModel: "MiniMax-Text-01",
    keyLabel: "MiniMax API key",
    keyHint: "Paste your API key",
    modelHint: "e.g. MiniMax-Text-01, abab6.5s-chat",
    keyRequired: true,
    keyUrl: "https://platform.minimaxi.com/user-center/basic-information/interface-key",
    tags: ['long_context'],
    accent: "#f97316",
  },
  nvidia: {
    id: "nvidia",
    label: "NVIDIA API",
    prompt: "NVIDIA API catalog.",
    defaultEndpoint: "https://integrate.api.nvidia.com/v1/chat/completions",
    defaultModel: "nvidia/llama-3.1-nemotron-70b-instruct",
    keyLabel: "NVIDIA API key",
    keyHint: "Paste your API key",
    modelHint: "e.g. nvidia/llama-3.1-nemotron-70b-instruct",
    keyRequired: true,
    keyUrl: "https://build.nvidia.com/",
    tags: ['fast', 'coding'],
    accent: "#76b900",
  },
  qwen: {
    id: "qwen",
    label: "Alibaba Qwen API",
    prompt: "Alibaba Qwen API.",
    defaultEndpoint: "https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions",
    defaultModel: "qwen-plus",
    keyLabel: "DashScope API key",
    keyHint: "Paste your API key",
    modelHint: "e.g. qwen-max, qwen-plus, qwen-turbo, qwen2.5-72b-instruct",
    keyRequired: true,
    keyUrl: "https://dashscope.console.aliyun.com/apiKey",
    tags: ['coding', 'cheap', 'reasoning'],
    accent: "#ef4444",
  },
  openrouter: {
    id: "openrouter",
    label: "OpenRouter API",
    prompt: "OpenRouter gives access to many models through one endpoint.",
    defaultEndpoint: "https://openrouter.ai/api/v1/chat/completions",
    defaultModel: "openai/gpt-4o-mini",
    keyLabel: "OpenRouter API key",
    keyHint: "Paste your API key",
    modelHint: "e.g. openai/gpt-4o, anthropic/claude-3.5-sonnet",
    keyRequired: true,
    keyUrl: "https://openrouter.ai/keys",
    tags: ['reasoning', 'vision'],
    accent: "#a855f7",
  },
  groq: {
    id: "groq",
    label: "Groq API",
    prompt: "Groq for extremely fast inference.",
    defaultEndpoint: "https://api.groq.com/openai/v1/chat/completions",
    defaultModel: "llama3-8b-8192",
    keyLabel: "Groq API key",
    keyHint: "Paste your API key",
    modelHint: "e.g. llama3-8b-8192, mixtral-8x7b-32768, gemma2-9b-it",
    keyRequired: true,
    keyUrl: "https://console.groq.com/keys",
    tags: ['fast', 'coding'],
    accent: "#f97316",
  },
  together: {
    id: "together",
    label: "Together AI API",
    prompt: "Together AI inference API for open-source models.",
    defaultEndpoint: "https://api.together.xyz/v1/chat/completions",
    defaultModel: "meta-llama/Llama-3.3-70B-Instruct-Turbo",
    keyLabel: "Together API key",
    keyHint: "Paste your API key",
    modelHint: "e.g. meta-llama/Llama-3.3-70B-Instruct-Turbo",
    keyRequired: true,
    keyUrl: "https://api.together.xyz/settings/api-keys",
    tags: ['coding', 'reasoning'],
    accent: "#6366f1",
  },
  fireworks: {
    id: "fireworks",
    label: "Fireworks AI API",
    prompt: "Fireworks AI fast inference.",
    defaultEndpoint: "https://api.fireworks.ai/inference/v1/chat/completions",
    defaultModel: "accounts/fireworks/models/llama-v3p1-70b-instruct",
    keyLabel: "Fireworks API key",
    keyHint: "Paste your API key",
    modelHint: "e.g. accounts/fireworks/models/llama-v3p1-70b-instruct",
    keyRequired: true,
    keyUrl: "https://fireworks.ai/account/api-keys",
    tags: ['fast', 'coding'],
    accent: "#d946ef",
  },
  cohere: {
    id: "cohere",
    label: "Cohere API",
    prompt: "Cohere command models via OpenAI-compatible endpoint.",
    defaultEndpoint: "https://api.cohere.com/compatibility/v1/chat/completions",
    defaultModel: "command-r-plus",
    keyLabel: "Cohere API key",
    keyHint: "Paste your API key",
    modelHint: "e.g. command-r-plus, command-r, command-a",
    keyRequired: true,
    keyUrl: "https://dashboard.cohere.com/api-keys",
    tags: ['long_context'],
    accent: "#ff6b6b",
  },
  mistral: {
    id: "mistral",
    label: "Mistral AI API",
    prompt: "Mistral AI API.",
    defaultEndpoint: "https://api.mistral.ai/v1/chat/completions",
    defaultModel: "mistral-large-latest",
    keyLabel: "Mistral API key",
    keyHint: "Paste your API key",
    modelHint: "e.g. mistral-large-latest, pixtral-large-latest, codestral-latest",
    keyRequired: true,
    keyUrl: "https://console.mistral.ai/api-keys/",
    tags: ['coding', 'fast'],
    accent: "#fa5025",
  },
  deepseek: {
    id: "deepseek",
    label: "DeepSeek API",
    prompt: "DeepSeek API.",
    defaultEndpoint: "https://api.deepseek.com/chat/completions",
    defaultModel: "deepseek-chat",
    keyLabel: "DeepSeek API key",
    keyHint: "Paste your API key",
    modelHint: "e.g. deepseek-chat, deepseek-reasoner",
    keyRequired: true,
    keyUrl: "https://platform.deepseek.com/api_keys",
    tags: ['reasoning', 'coding', 'cheap'],
    accent: "#4f46e5",
  },
  perplexity: {
    id: "perplexity",
    label: "Perplexity API",
    prompt: "Perplexity search-grounded API.",
    defaultEndpoint: "https://api.perplexity.ai/chat/completions",
    defaultModel: "sonar",
    keyLabel: "Perplexity API key",
    keyHint: "Paste your API key",
    modelHint: "e.g. sonar, sonar-pro, sonar-reasoning",
    keyRequired: true,
    keyUrl: "https://www.perplexity.ai/settings/api",
    tags: ['research'],
    accent: "#22d3ee",
  },
  xai: {
    id: "xai",
    label: "xAI Grok API",
    prompt: "xAI Grok API.",
    defaultEndpoint: "https://api.x.ai/v1/chat/completions",
    defaultModel: "grok-3-latest",
    keyLabel: "xAI API key",
    keyHint: "Paste your API key",
    modelHint: "e.g. grok-3-latest, grok-3-mini-latest",
    keyRequired: true,
    keyUrl: "https://console.x.ai/",
    tags: ['reasoning', 'coding'],
    accent: "#111827",
  },
  ai21: {
    id: "ai21",
    label: "AI21 Labs API",
    prompt: "AI21 Labs Jurassic / Jamba API.",
    defaultEndpoint: "https://api.ai21.com/studio/v1/chat/completions",
    defaultModel: "jamba-1.6-large",
    keyLabel: "AI21 API key",
    keyHint: "Paste your API key",
    modelHint: "e.g. jamba-1.6-large, jamba-1.6-mini",
    keyRequired: true,
    keyUrl: "https://studio.ai21.com/account/api-key",
    tags: ['long_context'],
    accent: "#7c3aed",
  },
  anyscale: {
    id: "anyscale",
    label: "Anyscale Endpoints",
    prompt: "Anyscale Endpoints for open-source models.",
    defaultEndpoint: "https://api.endpoints.anyscale.com/v1/chat/completions",
    defaultModel: "meta-llama/Llama-2-70b-chat-hf",
    keyLabel: "Anyscale API key",
    keyHint: "Paste your API key",
    modelHint: "e.g. meta-llama/Llama-2-70b-chat-hf",
    keyRequired: true,
    keyUrl: "https://app.endpoints.anyscale.com/credentials",
    tags: ['fast', 'coding'],
    accent: "#0ea5e9",
  },
  replicate: {
    id: "replicate",
    label: "Replicate API",
    prompt: "Replicate models via an OpenAI-compatible proxy.",
    defaultEndpoint: "https://api.replicate.com/v1/models/{owner}/{model}/predictions",
    defaultModel: "meta/meta-llama-3-70b-instruct",
    keyLabel: "Replicate API token",
    keyHint: "r8_...",
    modelHint: "Owner/model slug",
    keyRequired: true,
    keyUrl: "https://replicate.com/account/api-tokens",
    tags: ['coding'],
    accent: "#f43f5e",
  },
  huggingface: {
    id: "huggingface",
    label: "Hugging Face Inference API",
    prompt: "Hugging Face serverless inference endpoints.",
    defaultEndpoint: "https://api-inference.huggingface.co/models/{model}",
    defaultModel: "meta-llama/Llama-3.1-70B-Instruct",
    keyLabel: "Hugging Face token",
    keyHint: "hf_...",
    modelHint: "Full model id, e.g. meta-llama/Llama-3.1-70B-Instruct",
    keyRequired: true,
    keyUrl: "https://huggingface.co/settings/tokens",
    tags: ['coding'],
    accent: "#fbbf24",
  },
  cloudflare: {
    id: "cloudflare",
    label: "Cloudflare Workers AI",
    prompt: "Cloudflare Workers AI via OpenAI-compatible endpoint.",
    defaultEndpoint: "https://api.cloudflare.com/client/v4/accounts/{account_id}/ai/v1/chat/completions",
    defaultModel: "@cf/meta/llama-3.1-70b-instruct-awq",
    keyLabel: "Cloudflare API token",
    keyHint: "Paste your token",
    modelHint: "e.g. @cf/meta/llama-3.1-70b-instruct-awq",
    keyRequired: true,
    keyUrl: "https://dash.cloudflare.com/profile/api-tokens",
    tags: ['fast', 'cheap'],
    accent: "#f97316",
  },

  // Voice & media providers
  whisper: {
    id: "whisper",
    label: "Whisper (speech-to-text)",
    prompt: "OpenAI Whisper-compatible speech-to-text endpoint.",
    defaultEndpoint: "https://api.openai.com/v1/audio/transcriptions",
    defaultModel: "whisper-1",
    keyLabel: "API key",
    keyHint: "sk-... or any Whisper proxy key",
    modelHint: "whisper-1",
    keyRequired: true,
    keyUrl: "https://platform.openai.com/api-keys",
    accent: "#10a37f",
    isAudio: true,
  },
  openai_tts: {
    id: "openai_tts",
    label: "OpenAI Text-to-Speech",
    prompt: "OpenAI text-to-speech endpoint.",
    defaultEndpoint: "https://api.openai.com/v1/audio/speech",
    defaultModel: "tts-1",
    keyLabel: "OpenAI API key",
    keyHint: "sk-...",
    modelHint: "tts-1, tts-1-hd",
    keyRequired: true,
    keyUrl: "https://platform.openai.com/api-keys",
    accent: "#10a37f",
    isAudio: true,
  },
  elevenlabs_tts: {
    id: "elevenlabs_tts",
    label: "ElevenLabs Text-to-Speech",
    prompt: "ElevenLabs text-to-speech endpoint.",
    defaultEndpoint: "https://api.elevenlabs.io/v1/text-to-speech/{voice_id}",
    defaultModel: "eleven_multilingual_v2",
    keyLabel: "ElevenLabs API key",
    keyHint: "xi-...",
    modelHint: "Voice ID, e.g. 21m00Tcm4TlvDq8ikWAM",
    keyRequired: true,
    keyUrl: "https://elevenlabs.io/app/settings/api-keys",
    accent: "#6366f1",
    isAudio: true,
  },

  // Image generation providers
  dalle: {
    id: "dalle",
    label: "OpenAI DALL·E",
    prompt: "OpenAI DALL·E image generation endpoint.",
    defaultEndpoint: "https://api.openai.com/v1/images/generations",
    defaultModel: "dall-e-3",
    keyLabel: "OpenAI API key",
    keyHint: "sk-...",
    modelHint: "dall-e-3, dall-e-2",
    keyRequired: true,
    keyUrl: "https://platform.openai.com/api-keys",
    accent: "#10a37f",
    isImage: true,
  },
  stability: {
    id: "stability",
    label: "Stability AI",
    prompt: "Stability AI image generation endpoint.",
    defaultEndpoint: "https://api.stability.ai/v2beta/stable-image/generate/sd3",
    defaultModel: "sd3",
    keyLabel: "Stability API key",
    keyHint: "sk-...",
    modelHint: "sd3, sd3-turbo, sd3-large",
    keyRequired: true,
    keyUrl: "https://platform.stability.ai/account/keys",
    accent: "#f59e0b",
    isImage: true,
  },

  // Web search providers
  tavily: {
    id: "tavily",
    label: "Tavily Search",
    prompt: "Tavily search API for LLM-friendly web search results.",
    defaultEndpoint: "https://api.tavily.com/search",
    defaultModel: "tavily-api",
    keyLabel: "Tavily API key",
    keyHint: "tvly-...",
    modelHint: "tavily-api",
    keyRequired: true,
    keyUrl: "https://app.tavily.com/home",
    accent: "#22d3ee",
    isSearch: true,
  },
  brave_search: {
    id: "brave_search",
    label: "Brave Search",
    prompt: "Brave Search API for web results.",
    defaultEndpoint: "https://api.search.brave.com/res/v1/web/search",
    defaultModel: "brave-web",
    keyLabel: "Brave API key",
    keyHint: "BS...",
    modelHint: "brave-web",
    keyRequired: true,
    keyUrl: "https://api.search.brave.com/app/keys",
    accent: "#f97316",
    isSearch: true,
  },
  serpapi: {
    id: "serpapi",
    label: "SerpApi Search",
    prompt: "SerpApi for Google and other search engine results.",
    defaultEndpoint: "https://serpapi.com/search",
    defaultModel: "google",
    keyLabel: "SerpApi key",
    keyHint: "...",
    modelHint: "engine, e.g. google",
    keyRequired: true,
    keyUrl: "https://serpapi.com/manage-api-key",
    accent: "#3b82f6",
    isSearch: true,
  },

  // Embedding providers for RAG
  openai_embeddings: {
    id: "openai_embeddings",
    label: "OpenAI Embeddings",
    prompt: "OpenAI embeddings endpoint for vector search / RAG.",
    defaultEndpoint: "https://api.openai.com/v1/embeddings",
    defaultModel: "text-embedding-3-small",
    keyLabel: "OpenAI API key",
    keyHint: "sk-...",
    modelHint: "text-embedding-3-small, text-embedding-3-large",
    keyRequired: true,
    keyUrl: "https://platform.openai.com/api-keys",
    accent: "#10a37f",
    isEmbedding: true,
  },
  ollama_embeddings: {
    id: "ollama_embeddings",
    label: "Ollama Embeddings",
    prompt: "Ollama local embeddings endpoint.",
    defaultEndpoint: "http://localhost:11434/api/embeddings",
    defaultModel: "nomic-embed-text",
    keyLabel: "API key (optional)",
    keyHint: "Ollama ignores this unless an authenticating proxy requires it.",
    modelHint: "nomic-embed-text, mxbai-embed-large",
    keyRequired: false,
    accent: "#34c759",
    isEmbedding: true,
  },
  gemini_embeddings: {
    id: "gemini_embeddings",
    label: "Google Gemini Embeddings",
    prompt: "Google Gemini embeddings endpoint.",
    defaultEndpoint: "https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:embedContent",
    defaultModel: "text-embedding-004",
    keyLabel: "Google AI Studio key",
    keyHint: "Paste your API key",
    modelHint: "text-embedding-004",
    keyRequired: true,
    keyUrl: "https://aistudio.google.com/app/apikey",
    accent: "#4285f4",
    isEmbedding: true,
  },

  custom: {
    id: "custom",
    label: "Custom API endpoint",
    prompt: "Any OpenAI-compatible API endpoint or proxy.",
    defaultEndpoint: "https://example.com/v1/chat/completions",
    defaultModel: "model-name",
    keyLabel: "API key (optional)",
    keyHint: "Leave blank if the endpoint needs no key",
    modelHint: "Any model name supported by the endpoint",
    keyRequired: false,
    accent: "#6c8cff",
  },
};

export const CONNECTION_TYPE_ORDER = [
  // Most popular / most used first
  "openai",
  "anthropic",
  "gemini",
  "openrouter",
  "ollama",
  "llamacpp",
  "groq",
  "azure",
  "deepseek",
  "mistral",
  "xai",
  "cohere",
  "qwen",
  "moonshot",
  "zhipu",
  "minimax",
  "perplexity",
  "nvidia",
  "together",
  "fireworks",
  "huggingface",
  "replicate",
  "cloudflare",
  "ai21",
  "bedrock",
  "vertex",
  "anyscale",
  // Voice & media
  "dalle",
  "stability",
  "whisper",
  "openai_tts",
  "elevenlabs_tts",
  // Search & embeddings
  "tavily",
  "brave_search",
  "serpapi",
  "openai_embeddings",
  "ollama_embeddings",
  "gemini_embeddings",
  "custom",
];

export function typeById(id) {
  return CONNECTION_TYPES[id];
}

// Backwards-compatible provider data kept for import migrations.
export const PROVIDERS = {
  local: { id: "local", label: "Local (Ollama)", endpoint: "", defaultModel: "llama3.2", noKeyRequired: true },
  glm: { id: "glm", label: "GLM (Zhipu)", endpoint: "https://open.bigmodel.cn/api/paas/v4/chat/completions", defaultModel: "glm-4-plus" },
  kimi: { id: "kimi", label: "Kimi (Moonshot)", endpoint: "https://api.moonshot.cn/v1/chat/completions", defaultModel: "moonshot-v1-8k" },
  minimax: { id: "minimax", label: "MiniMax", endpoint: "https://api.minimaxi.com/v1/chat/completions", defaultModel: "MiniMax-Text-01" },
  nemotron: { id: "nemotron", label: "Nemotron (NVIDIA)", endpoint: "https://integrate.api.nvidia.com/v1/chat/completions", defaultModel: "nvidia/llama-3.1-nemotron-70b-instruct" },
  gemma: { id: "gemma", label: "Gemma (Google AI)", endpoint: "https://generativelanguage.googleapis.com/v1beta/openai/chat/completions", defaultModel: "gemma-3-27b-it" },
  qwen: { id: "qwen", label: "Qwen (DashScope)", endpoint: "https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions", defaultModel: "qwen-plus" },
};

export const PROVIDER_ORDER = ["local", "glm", "kimi", "minimax", "nemotron", "gemma", "qwen"];

// Default agent presets shipped with the app. These are fixed — their prompts
// cannot be edited from the UI. Users may add custom agents on top of them.
// Folder/file tool access is granted automatically at runtime whenever a folder
// or file is linked; agents do not need a special "(folder)" variant.
export const DEFAULT_AGENTS = [
  {
    id: "agent_auto",
    label: "Auto agent",
    prompt: "You are the Auto Agent. Automatically choose the best response format, depth, model, and workflow for each request. Use a single sentence for trivial questions, bullets for lists, one Markdown table for data comparisons, structured research sections with inline citations for research questions, and deep 10W-framework reports for broad/complex topics. For coding or PWA tasks, write production-grade, tested, repository-aware code and use file tools when a folder or file is linked. Avoid unnecessary questions; make reasonable assumptions and answer context-first.",
    enabled: true,
    tags: ['chat', 'general', 'auto'],
    autoTags: ["help", "assistant", "general", "what is", "how do i", "should i", "auto", "best", "choose"],
  },
  {
    id: "agent_minimal",
    label: "Minimal agent",
    prompt: "You are the Minimal Agent. Respond in a single sentence only. Never use lists, tables, headings, or extra explanation.",
    enabled: true,
    tags: ['minimal', 'cheap'],
    autoTags: ["minimal", "one sentence", "short", "brief", "quick", "single sentence", "tl;dr"],
  },
  {
    id: "agent_bullet",
    label: "Bullet agent",
    prompt: "You are the Bullet Agent. Respond only as bullet points or a numbered list. No titles, no subtitles, no explanations outside the list, and one line per bullet.",
    enabled: true,
    tags: ['bullet', 'list'],
    autoTags: ["bullet", "bullets", "list", "points", "numbered", "key points", "outline"],
  },
  {
    id: "agent_table",
    label: "Table agent",
    prompt: "You are the Table Agent. Respond with exactly one Markdown table only. No explanation outside the table, no title, and keep wording short.",
    enabled: true,
    tags: ['table', 'data'],
    autoTags: ["table", "compare", "comparison", "matrix", "score", "ranking", "tabular", "columns"],
  },
  {
    id: "agent_research",
    label: "Research agent",
    prompt: "You are the Research Agent. Perform thorough online research, validate sources, and structure every answer as: Title, Situation Analysis, Current State, Findings, Recommendations, Implementation Plan, Risks, References. Use inline numbered citations [1], [2], etc. in every section and provide a traceable reference list. Prioritize official documentation, government sources, academic sources, company publications, and industry publications. Never ask clarification questions; make reasonable assumptions and build a complete, evidence-based answer automatically.",
    enabled: true,
    tags: ['research', 'search'],
    autoTags: ["research", "report", "sources", "citations", "findings", "references", "white paper", "technical report", "investigate"],
  },
  {
    id: "agent_max",
    label: "Max agent",
    prompt: "You are the Max Agent. For complex requests, recommend the best deliverable type (white paper, research paper, feasibility study, technical design, newsletter), then generate a complete research-grade document using the 10W framework: Who, What, Where, When, Why, How, For Whom, Resources, Status, Outcome. Include UML/process diagrams in text, quantitative and qualitative analysis, APA-style references with citation numbering, roadmaps, and a references section. When suitable, output a complete HTML document. Validate every source and URL.",
    enabled: true,
    tags: ['max', 'report'],
    autoTags: ["max", "white paper", "feasibility", "technical design", "complete document", "10w", "comprehensive", "in depth"],
  },
  {
    id: "agent_code",
    label: "Coding agent",
    prompt: "You are the Coding Agent. Follow the workflow: Analyze → Plan → Generate → Review → Refactor → Optimize → Test → Document. Write production-grade, repository-aware, multi-file code when needed, and refactor existing code when asked. When a folder or file is linked, use file tools to read, write, patch, and search. Provide runnable code, tests, and clear usage instructions. Prefer tested, GitHub-ready output.",
    enabled: true,
    tags: ['coding'],
    autoTags: ["code", "program", "script", "function", "class", "debug", "refactor", "test", "github", "repository", "typescript", "python", "javascript"],
  },
  {
    id: "agent_pwa",
    label: "PWA agent",
    prompt: "You are the PWA Agent. Build production-ready Progressive Web Apps. Ensure offline support, a service worker, responsive design, installability, GitHub Pages deployment, CLI integration, and an optional Python backend when requested. Follow the build flow: PWA → Frontend → API → CLI Connector → Model Runtime → Ollama/vLLM. Use file tools when a folder or file is linked and deliver tested, deployable code.",
    enabled: true,
    tags: ['pwa', 'coding'],
    autoTags: ["pwa", "progressive web app", "service worker", "offline", "manifest", "github pages", "deploy", "installable", "responsive"],
  },
  {
    id: "agent_image",
    label: "Image creator",
    prompt: "You are the Image Creator agent. When the user asks for an image, describe what should be generated concisely and trigger the configured image-generation connection. Otherwise answer normally.",
    enabled: true,
    tags: ['image'],
    autoTags: ["image", "picture", "photo", "draw", "generate image", "create image", "illustration", "diagram"],
  },
];

export const DEFAULT_AGENT_IDS = new Set(DEFAULT_AGENTS.map((a) => a.id));
